server.port=8082
spring.datasource.url=jdbc:mysql://localhost:3306/track_my_bus?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Set your actual MySQL password here (leave blank if you use XAMPP or default MySQL without password)
spring.datasource.password=0206
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
